server:
    port: 8000
spring:
    application:
        name: eureka-client-tester
    cloud: 
        client:
            ipAddress: localhost
eureka: 
    instance: 
        #会出现在服务列表的Status里，并且点击的连接也是它
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
        prefer-ip-address: true
        leaseRenewalIntervalInSeconds: 10
    client: 
        service-url: 
            default-zone: http://localhost:8761/eureka/
        #enabled: true
        #register-with-eureka: true
        #fetch-registry: true
        #healthcheck: 
            #enable: true